use std::fmt::Write as _;

use quote::ToTokens;
use syn::visit::Visit;

use crate::expand::KernelOptions;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ParameterFlavor {
    Invocation,
    StorageRead,
    StorageReadWrite,
    Uniform,
    Value,
}

pub fn parameter_flavor(ty: &syn::Type) -> ParameterFlavor {
    let Some(name) = type_name(ty) else {
        return ParameterFlavor::Value;
    };
    match name.as_str() {
        "Invocation" | "SV_DispatchThreadID" | "UVec3" => ParameterFlavor::Invocation,
        "Storage" | "StructuredBuffer" => ParameterFlavor::StorageRead,
        "StorageMut" | "RWStructuredBuffer" => ParameterFlavor::StorageReadWrite,
        "Uniform" | "ConstantBuffer" => ParameterFlavor::Uniform,
        _ => ParameterFlavor::Value,
    }
}

pub fn emit_kernel(
    module: &syn::ItemMod,
    kernel: &syn::ItemFn,
    options: KernelOptions,
) -> syn::Result<String> {
    let (_, items) = module.content.as_ref().expect("validated inline module");
    let mut output = String::new();
    writeln!(
        output,
        "// Generated by gpu-dialect from Rust syntax. Slang is the compiler backend."
    )
    .unwrap();
    writeln!(output).unwrap();

    // Slang overload resolution distinguishes Rust's boolean and bitwise `!`.
    // Forwarding `!` verbatim would silently turn integer complement into a test.
    let mut not = NotUsage(false);
    not.visit_item_mod(module);
    if not.0 {
        writeln!(output, "bool __gust_not(bool value) {{ return !value; }}").unwrap();
        writeln!(output, "int __gust_not(int value) {{ return ~value; }}").unwrap();
        writeln!(output, "uint __gust_not(uint value) {{ return ~value; }}\n").unwrap();
    }

    for item in items {
        if let syn::Item::Struct(item) = item {
            emit_struct(&mut output, item)?;
        }
    }

    let mut binding = 0_u32;
    let mut resources = Vec::new();
    let mut invocation = None;
    for argument in &kernel.sig.inputs {
        let (name, ty) = typed_argument(argument)?;
        match parameter_flavor(ty) {
            ParameterFlavor::Invocation => invocation = Some(name.to_string()),
            ParameterFlavor::StorageRead | ParameterFlavor::StorageReadWrite => {
                let element = wrapper_element_type(ty)?;
                let wrapper = if parameter_flavor(ty) == ParameterFlavor::StorageRead {
                    "StructuredBuffer"
                } else {
                    "RWStructuredBuffer"
                };
                writeln!(
                    output,
                    "[[vk::binding({binding}, 0)]] {wrapper}<{}> {name};",
                    emit_type(element)?
                )
                .unwrap();
                resources.push(name.to_string());
                binding += 1;
            }
            ParameterFlavor::Uniform => {
                let element = wrapper_element_type(ty)?;
                writeln!(
                    output,
                    "[[vk::binding({binding}, 0)]] ConstantBuffer<{}> {name};",
                    emit_type(element)?
                )
                .unwrap();
                binding += 1;
            }
            ParameterFlavor::Value => {
                return Err(syn::Error::new_spanned(
                    ty,
                    "Slang compute entry points currently accept resources and SV_DispatchThreadID only",
                ));
            }
        }
    }
    writeln!(output).unwrap();

    for item in items {
        let syn::Item::Fn(function) = item else {
            continue;
        };
        if function.sig.ident == kernel.sig.ident
            || crate::expand::kernel_options(function)?.is_some()
        {
            continue;
        }
        emit_helper(&mut output, function)?;
    }

    let invocation = invocation.ok_or_else(|| {
        syn::Error::new_spanned(
            &kernel.sig,
            "a Slang kernel requires an `SV_DispatchThreadID` (or legacy `Invocation`) parameter",
        )
    })?;
    let [x, y, z] = options.workgroup_size;
    let entry_point = format!("gpu_{}_{}", module.ident, kernel.sig.ident);
    writeln!(output, "[shader(\"compute\")]").unwrap();
    writeln!(output, "[numthreads({x}, {y}, {z})]").unwrap();
    writeln!(
        output,
        "void {entry_point}(uint3 {invocation} : SV_DispatchThreadID)"
    )
    .unwrap();
    writeln!(output, "{{").unwrap();
    for resource in &resources {
        writeln!(output, "    uint __gpu_len_{resource};").unwrap();
        writeln!(output, "    uint __gpu_stride_{resource};").unwrap();
        writeln!(
            output,
            "    {resource}.GetDimensions(__gpu_len_{resource}, __gpu_stride_{resource});"
        )
        .unwrap();
    }
    emit_statements(&mut output, &kernel.block.stmts, 1, false)?;
    writeln!(output, "}}").unwrap();
    Ok(output)
}

fn emit_struct(output: &mut String, item: &syn::ItemStruct) -> syn::Result<()> {
    writeln!(output, "struct {}", item.ident).unwrap();
    writeln!(output, "{{").unwrap();
    let syn::Fields::Named(fields) = &item.fields else {
        unreachable!("validated named fields")
    };
    for field in &fields.named {
        let name = field.ident.as_ref().expect("named field");
        writeln!(output, "    {} {name};", emit_type(&field.ty)?).unwrap();
    }
    writeln!(output, "}};\n").unwrap();
    Ok(())
}

fn emit_helper(output: &mut String, function: &syn::ItemFn) -> syn::Result<()> {
    let return_type = match &function.sig.output {
        syn::ReturnType::Default => "void".to_owned(),
        syn::ReturnType::Type(_, ty) => emit_type(ty)?,
    };
    write!(output, "{return_type} {}(", function.sig.ident).unwrap();
    for (index, argument) in function.sig.inputs.iter().enumerate() {
        if index != 0 {
            write!(output, ", ").unwrap();
        }
        let (name, ty) = typed_argument(argument)?;
        write!(output, "{} {name}", emit_type(ty)?).unwrap();
    }
    writeln!(output, ")").unwrap();
    writeln!(output, "{{").unwrap();
    emit_statements(output, &function.block.stmts, 1, return_type != "void")?;
    writeln!(output, "}}\n").unwrap();
    Ok(())
}

fn emit_statements(
    output: &mut String,
    statements: &[syn::Stmt],
    indent: usize,
    return_tail: bool,
) -> syn::Result<()> {
    for (index, statement) in statements.iter().enumerate() {
        let is_tail = return_tail && index + 1 == statements.len();
        let padding = "    ".repeat(indent);
        match statement {
            syn::Stmt::Local(local) => {
                let (pattern, annotation) = local_binding(&local.pat)?;
                let declaration = annotation
                    .map(emit_type)
                    .transpose()?
                    .unwrap_or_else(|| "var".to_owned());
                let initial = local.init.as_ref().ok_or_else(|| {
                    syn::Error::new_spanned(local, "Slang let bindings require an initializer")
                })?;
                writeln!(
                    output,
                    "{padding}{declaration} {} = {};",
                    pattern.ident,
                    emit_expression(&initial.expr)?
                )
                .unwrap();
            }
            syn::Stmt::Expr(expression, semicolon) => match expression {
                syn::Expr::If(expression) => {
                    emit_if(output, expression, indent, is_tail && semicolon.is_none())?
                }
                syn::Expr::Block(expression) => {
                    writeln!(output, "{padding}{{").unwrap();
                    emit_statements(
                        output,
                        &expression.block.stmts,
                        indent + 1,
                        is_tail && semicolon.is_none(),
                    )?;
                    writeln!(output, "{padding}}}").unwrap();
                }
                _ => {
                    let prefix = if is_tail
                        && semicolon.is_none()
                        && !matches!(expression, syn::Expr::Return(_))
                    {
                        "return "
                    } else {
                        ""
                    };
                    writeln!(output, "{padding}{prefix}{};", emit_expression(expression)?).unwrap();
                }
            },
            syn::Stmt::Item(item) => {
                return Err(syn::Error::new_spanned(
                    item,
                    "items inside Slang functions are not supported",
                ));
            }
            syn::Stmt::Macro(item) => {
                return Err(syn::Error::new_spanned(item, "macros cannot run in Slang"));
            }
        }
    }
    Ok(())
}

pub fn local_binding(pattern: &syn::Pat) -> syn::Result<(&syn::PatIdent, Option<&syn::Type>)> {
    match pattern {
        syn::Pat::Ident(name) => Ok((name, None)),
        syn::Pat::Type(typed) => match typed.pat.as_ref() {
            syn::Pat::Ident(name) => Ok((name, Some(&typed.ty))),
            _ => Err(syn::Error::new_spanned(
                pattern,
                "GPU let bindings require a single identifier, optionally with a type",
            )),
        },
        _ => Err(syn::Error::new_spanned(
            pattern,
            "GPU let bindings require a single identifier, optionally with a type",
        )),
    }
}

fn emit_if(
    output: &mut String,
    expression: &syn::ExprIf,
    indent: usize,
    return_tail: bool,
) -> syn::Result<()> {
    let padding = "    ".repeat(indent);
    writeln!(
        output,
        "{padding}if ({})",
        emit_expression(&expression.cond)?
    )
    .unwrap();
    writeln!(output, "{padding}{{").unwrap();
    emit_statements(
        output,
        &expression.then_branch.stmts,
        indent + 1,
        return_tail,
    )?;
    writeln!(output, "{padding}}}").unwrap();
    if let Some((_, alternative)) = &expression.else_branch {
        if let syn::Expr::If(nested) = alternative.as_ref() {
            write!(output, "{padding}else ").unwrap();
            emit_if(output, nested, indent, return_tail)?;
        } else {
            writeln!(output, "{padding}else").unwrap();
            writeln!(output, "{padding}{{").unwrap();
            match alternative.as_ref() {
                syn::Expr::Block(block) => {
                    emit_statements(output, &block.block.stmts, indent + 1, return_tail)?
                }
                other => writeln!(
                    output,
                    "{}{};",
                    "    ".repeat(indent + 1),
                    emit_expression(other)?
                )
                .unwrap(),
            }
            writeln!(output, "{padding}}}").unwrap();
        }
    }
    Ok(())
}

fn emit_expression(expression: &syn::Expr) -> syn::Result<String> {
    Ok(match expression {
        syn::Expr::Array(array) => format!(
            "{{ {} }}",
            array
                .elems
                .iter()
                .map(emit_expression)
                .collect::<syn::Result<Vec<_>>>()?
                .join(", ")
        ),
        syn::Expr::Assign(assign) => format!(
            "{} = {}",
            emit_expression(&assign.left)?,
            emit_expression(&assign.right)?
        ),
        syn::Expr::Binary(binary) => format!(
            "({} {} {})",
            emit_expression(&binary.left)?,
            binary.op.to_token_stream(),
            emit_expression(&binary.right)?
        ),
        syn::Expr::Call(call) => format!(
            "{}({})",
            emit_expression(&call.func)?,
            call.args
                .iter()
                .map(emit_expression)
                .collect::<syn::Result<Vec<_>>>()?
                .join(", ")
        ),
        syn::Expr::Cast(cast) => {
            format!("{}({})", emit_type(&cast.ty)?, emit_expression(&cast.expr)?)
        }
        syn::Expr::Field(field) => format!(
            "{}.{}",
            emit_expression(&field.base)?,
            field.member.to_token_stream()
        ),
        syn::Expr::Group(group) => emit_expression(&group.expr)?,
        syn::Expr::Index(index) => format!(
            "{}[{}]",
            emit_expression(&index.expr)?,
            emit_expression(&index.index)?
        ),
        syn::Expr::Lit(literal) => emit_literal(&literal.lit)?,
        syn::Expr::MethodCall(call) if call.method == "global_id" => {
            emit_expression(&call.receiver)?
        }
        syn::Expr::MethodCall(call) if call.method == "len" => {
            let receiver = emit_expression(&call.receiver)?;
            format!("__gpu_len_{receiver}")
        }
        syn::Expr::Paren(paren) => format!("({})", emit_expression(&paren.expr)?),
        syn::Expr::Path(path) => path.path.to_token_stream().to_string().replace(" :: ", "."),
        syn::Expr::Return(expression) => match &expression.expr {
            Some(value) => format!("return {}", emit_expression(value)?),
            None => "return".to_owned(),
        },
        syn::Expr::Struct(value) => {
            return Err(syn::Error::new_spanned(
                value,
                "GPU struct literals need field-aware lowering and are not supported yet; copy a buffer element and update its fields",
            ));
        }
        syn::Expr::Unary(unary) if matches!(unary.op, syn::UnOp::Not(_)) => {
            format!("__gust_not({})", emit_expression(&unary.expr)?)
        }
        syn::Expr::Unary(unary) => format!(
            "({}{})",
            unary.op.to_token_stream(),
            emit_expression(&unary.expr)?
        ),
        other => {
            return Err(syn::Error::new_spanned(
                other,
                "this Rust expression is not in the Rust-to-Slang subset yet",
            ));
        }
    })
}

struct NotUsage(bool);

impl<'ast> Visit<'ast> for NotUsage {
    fn visit_expr_unary(&mut self, expression: &'ast syn::ExprUnary) {
        self.0 |= matches!(expression.op, syn::UnOp::Not(_));
        syn::visit::visit_expr_unary(self, expression);
    }
}

fn emit_literal(literal: &syn::Lit) -> syn::Result<String> {
    let unsupported = || {
        syn::Error::new_spanned(
            literal,
            "GPU literals support booleans and 32-bit numbers (i32, u32, f32) only",
        )
    };
    match literal {
        syn::Lit::Bool(value) => Ok(value.value.to_string()),
        syn::Lit::Int(value) => {
            let digits = value.base10_digits();
            match value.suffix() {
                "" => Ok(digits.to_owned()),
                "u32" => Ok(format!("uint({digits})")),
                "i32" => Ok(format!("int({digits})")),
                "f32" => Ok(format!("float({digits}.0)")),
                _ => Err(unsupported()),
            }
        }
        syn::Lit::Float(value) => match value.suffix() {
            "" => Ok(value.base10_digits().to_owned()),
            "f32" => Ok(format!("float({})", value.base10_digits())),
            _ => Err(unsupported()),
        },
        _ => Err(unsupported()),
    }
}

fn emit_type(ty: &syn::Type) -> syn::Result<String> {
    if matches!(ty, syn::Type::Tuple(tuple) if tuple.elems.is_empty()) {
        return Ok("void".to_owned());
    }
    let syn::Type::Path(path) = ty else {
        return Err(syn::Error::new_spanned(
            ty,
            "Slang types must be named paths",
        ));
    };
    let segment = path.path.segments.last().expect("nonempty type path");
    let name = match segment.ident.to_string().as_str() {
        "f32" | "float" => "float".to_owned(),
        "i32" | "int" => "int".to_owned(),
        "u32" | "uint" => "uint".to_owned(),
        "bool" => "bool".to_owned(),
        "UVec3" | "SV_DispatchThreadID" => "uint3".to_owned(),
        name => name.to_owned(),
    };
    let syn::PathArguments::AngleBracketed(arguments) = &segment.arguments else {
        return Ok(name);
    };
    let parameters = arguments
        .args
        .iter()
        .filter_map(|argument| match argument {
            syn::GenericArgument::Type(ty) => Some(emit_type(ty)),
            _ => None,
        })
        .collect::<syn::Result<Vec<_>>>()?;
    Ok(format!("{name}<{}>", parameters.join(", ")))
}

fn typed_argument(argument: &syn::FnArg) -> syn::Result<(&syn::Ident, &syn::Type)> {
    let syn::FnArg::Typed(argument) = argument else {
        return Err(syn::Error::new_spanned(
            argument,
            "GPU functions cannot use self",
        ));
    };
    let syn::Pat::Ident(pattern) = argument.pat.as_ref() else {
        return Err(syn::Error::new_spanned(
            &argument.pat,
            "GPU parameters need identifier names",
        ));
    };
    Ok((&pattern.ident, &argument.ty))
}

pub fn wrapper_element_type(ty: &syn::Type) -> syn::Result<&syn::Type> {
    let syn::Type::Path(path) = ty else {
        return Err(syn::Error::new_spanned(
            ty,
            "GPU resource requires a named element type",
        ));
    };
    let segment = path.path.segments.last().expect("nonempty resource type");
    let syn::PathArguments::AngleBracketed(arguments) = &segment.arguments else {
        return Err(syn::Error::new_spanned(
            segment,
            "GPU resource requires one element type",
        ));
    };
    arguments
        .args
        .iter()
        .find_map(|argument| match argument {
            syn::GenericArgument::Type(ty) => Some(ty),
            _ => None,
        })
        .ok_or_else(|| syn::Error::new_spanned(arguments, "GPU resource requires an element type"))
}

fn type_name(ty: &syn::Type) -> Option<String> {
    let syn::Type::Path(path) = ty else {
        return None;
    };
    path.path
        .segments
        .last()
        .map(|segment| segment.ident.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn emits_slang_resources_semantic_and_body() {
        let module: syn::ItemMod = syn::parse_quote! {
            mod vector_add {
                #[kernel(workgroup_size(64, 1, 1))]
                fn add(id: SV_DispatchThreadID, a: StructuredBuffer<float>, mut out: RWStructuredBuffer<float>) {
                    let i = id.x;
                    if i < out.len() {
                        out[i] = a[i] + 1.0;
                    }
                }
            }
        };
        let (_, items) = module.content.as_ref().unwrap();
        let kernel = items
            .iter()
            .find_map(|item| match item {
                syn::Item::Fn(function) => Some(function),
                _ => None,
            })
            .unwrap();
        let source = emit_kernel(
            &module,
            kernel,
            KernelOptions {
                workgroup_size: [64, 1, 1],
            },
        )
        .unwrap();
        assert!(source.contains("StructuredBuffer<float> a;"));
        assert!(source.contains("RWStructuredBuffer<float> out;"));
        assert!(source.contains("void gpu_vector_add_add(uint3 id : SV_DispatchThreadID)"));
        assert!(source.contains("out[i] = (a[i] + 1.0);"));
        assert!(source.contains("i < __gpu_len_out"));
    }
}
