use std::{fmt, fmt::Write as _};

use gpu_dialect::{Access, KernelDescriptor};

use crate::{Error, validate_kernel};

/// Render the descriptor-specific wgpu host code used to encode a dispatch.
///
/// The generated source intentionally starts with already-created `wgpu::Buffer`
/// parameters so the binding layout, shader/pipeline construction, and dispatch
/// mechanics remain easy to inspect without including upload/readback policy.
pub fn render_wgpu_source(kernel: &KernelDescriptor) -> Result<String, Error> {
    let resources = validate_kernel(kernel)?;
    let pipeline_type = format!(
        "{}{}Pipeline",
        rust_type_identifier(kernel.module),
        rust_type_identifier(kernel.name)
    );
    let mut source = String::new();
    write_line(
        &mut source,
        format_args!(
            "// @generated by gpu-dialect-wgpu for {}",
            kernel.qualified_name()
        ),
    );
    write_line(
        &mut source,
        format_args!("// Shader source: Rust -> Slang -> WGSL"),
    );
    for parameter in &resources {
        let binding = parameter.binding.expect("validated resource binding");
        let layout = parameter
            .resource_layout
            .expect("validated resource layout");
        write_line(
            &mut source,
            format_args!(
                "// @group({}) @binding({}) {}: {} [{}; size={}, align={}, stride={}]",
                binding.group,
                binding.binding,
                parameter.name,
                layout.element.name,
                match layout.rules {
                    gpu_dialect::ShaderLayoutRules::StorageV1 => "storage-v1",
                },
                layout.element.size,
                layout.element.alignment,
                layout.element_stride,
            ),
        );
        render_struct_fields(&mut source, parameter.name, layout.element, 0);
    }
    write_line(
        &mut source,
        format_args!("// Construct this pipeline once, then reuse encode() for every dispatch."),
    );
    write_line(
        &mut source,
        format_args!("// Call encode() repeatedly on one command encoder to batch dispatches."),
    );
    source.push('\n');
    write_line(&mut source, format_args!("pub struct {pipeline_type} {{"));
    source.push_str("    _shader: wgpu::ShaderModule,\n");
    source.push_str("    bind_group_layout: wgpu::BindGroupLayout,\n");
    source.push_str("    _pipeline_layout: wgpu::PipelineLayout,\n");
    source.push_str("    pipeline: wgpu::ComputePipeline,\n");
    source.push_str("}\n\n");
    write_line(&mut source, format_args!("impl {pipeline_type} {{"));
    source.push_str(
        "    pub fn new(device: &wgpu::Device, descriptor: &gpu_dialect::KernelDescriptor) -> Self {\n",
    );
    write_line(
        &mut source,
        format_args!(
            "        let label = \"{}::{}\";",
            kernel.module, kernel.name
        ),
    );
    source.push_str(
        "        let wgsl = gpu_dialect::slang::compile_wgsl(descriptor).expect(\"compile generated Slang\");\n",
    );
    source.push_str(
        "        let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {\n",
    );
    source.push_str("            label: Some(label),\n");
    source.push_str("            source: wgpu::ShaderSource::Wgsl(wgsl.into()),\n");
    source.push_str("        });\n\n");
    source.push_str("        let layout_entries = [\n");
    for parameter in &resources {
        let binding = parameter.binding.expect("validated resource binding");
        source.push_str("            wgpu::BindGroupLayoutEntry {\n");
        write_line(
            &mut source,
            format_args!("                binding: {},", binding.binding),
        );
        source.push_str("                visibility: wgpu::ShaderStages::COMPUTE,\n");
        source.push_str("                ty: wgpu::BindingType::Buffer {\n");
        write_line(
            &mut source,
            format_args!(
                "                    ty: wgpu::BufferBindingType::Storage {{ read_only: {} }},",
                parameter.access == Access::ReadOnly
            ),
        );
        source.push_str("                    has_dynamic_offset: false,\n");
        source.push_str("                    min_binding_size: None,\n");
        source.push_str("                },\n");
        source.push_str("                count: None,\n");
        source.push_str("            },\n");
    }
    source.push_str("        ];\n");
    source.push_str(
        "        let bind_group_layout = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {\n            label: Some(label),\n            entries: &layout_entries,\n        });\n",
    );
    source.push_str(
        "        let pipeline_layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {\n            label: Some(label),\n            bind_group_layouts: &[Some(&bind_group_layout)],\n            immediate_size: 0,\n        });\n",
    );
    source.push_str(
        "        let pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {\n            label: Some(label),\n            layout: Some(&pipeline_layout),\n            module: &shader,\n            entry_point: Some(descriptor.entry_point),\n            compilation_options: Default::default(),\n            cache: None,\n        });\n        Self {\n            _shader: shader,\n            bind_group_layout,\n            _pipeline_layout: pipeline_layout,\n            pipeline,\n        }\n    }\n\n",
    );
    source.push_str("    pub fn encode(\n");
    source.push_str("        &self,\n");
    source.push_str("        device: &wgpu::Device,\n");
    source.push_str("        encoder: &mut wgpu::CommandEncoder,\n");
    source.push_str("        element_count: u32,\n");
    for parameter in &resources {
        write_line(
            &mut source,
            format_args!("        {}: &wgpu::Buffer,", parameter.name),
        );
    }
    source.push_str("    ) {\n");
    write_line(
        &mut source,
        format_args!(
            "        let label = \"{}::{}\";",
            kernel.module, kernel.name
        ),
    );
    source.push_str("        let bind_group_entries = [\n");
    for parameter in &resources {
        let binding = parameter.binding.expect("validated resource binding");
        source.push_str("            wgpu::BindGroupEntry {\n");
        write_line(
            &mut source,
            format_args!("                binding: {},", binding.binding),
        );
        write_line(
            &mut source,
            format_args!(
                "                resource: {}.as_entire_binding(),",
                parameter.name
            ),
        );
        source.push_str("            },\n");
    }
    source.push_str("        ];\n");
    source.push_str(
        "        let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {\n            label: Some(label),\n            layout: &self.bind_group_layout,\n            entries: &bind_group_entries,\n        });\n\n",
    );
    source.push_str(
        "        let mut pass = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor {\n            label: Some(label),\n            timestamp_writes: None,\n        });\n        pass.set_pipeline(&self.pipeline);\n        pass.set_bind_group(0, &bind_group, &[]);\n",
    );
    write_line(
        &mut source,
        format_args!(
            "        pass.dispatch_workgroups(element_count.div_ceil({}), 1, 1);",
            kernel.workgroup_size[0]
        ),
    );
    source.push_str("    }\n}\n");
    Ok(source)
}

fn render_struct_fields(
    target: &mut String,
    path: &str,
    layout: gpu_dialect::TypeLayout,
    base_offset: u32,
) {
    if let gpu_dialect::TypeLayoutKind::Struct(fields) = layout.kind {
        for field in fields {
            let path = format!("{path}.{}", field.name);
            let offset = base_offset + field.offset;
            write_line(
                target,
                format_args!(
                    "//   {path}: {} @ byte {offset} (size={})",
                    field.ty.name, field.ty.size
                ),
            );
            render_struct_fields(target, &path, field.ty, offset);
        }
    }
}

fn rust_type_identifier(value: &str) -> String {
    let mut result = String::new();
    let mut uppercase_next = true;
    for character in value.chars() {
        if !character.is_ascii_alphanumeric() {
            uppercase_next = true;
        } else if uppercase_next {
            result.push(character.to_ascii_uppercase());
            uppercase_next = false;
        } else {
            result.push(character);
        }
    }
    result
}

fn write_line(target: &mut String, arguments: fmt::Arguments<'_>) {
    target
        .write_fmt(arguments)
        .expect("writing into a String cannot fail");
    target.push('\n');
}
