// @generated by gpu-dialect-wgpu for pool::integrate
// Shader source: Rust -> Slang -> WGSL
// @group(0) @binding(0) active: Active [storage-v1; size=4, align=4, stride=4]
//   active.count: u32 @ byte 0 (size=4)
// @group(0) @binding(1) settings: Settings [storage-v1; size=12, align=4, stride=12]
//   settings.dt: f32 @ byte 0 (size=4)
//   settings.gravity: f32 @ byte 4 (size=4)
//   settings.budget: u32 @ byte 8 (size=4)
// @group(0) @binding(2) particles: Particle [storage-v1; size=20, align=4, stride=20]
//   particles.x: f32 @ byte 0 (size=4)
//   particles.y: f32 @ byte 4 (size=4)
//   particles.vx: f32 @ byte 8 (size=4)
//   particles.vy: f32 @ byte 12 (size=4)
//   particles.steps: u32 @ byte 16 (size=4)
// Construct this pipeline once, then reuse encode() for every dispatch.
// Call encode() repeatedly on one command encoder to batch dispatches.

pub struct PoolIntegratePipeline {
    _shader: wgpu::ShaderModule,
    bind_group_layout: wgpu::BindGroupLayout,
    _pipeline_layout: wgpu::PipelineLayout,
    pipeline: wgpu::ComputePipeline,
}

impl PoolIntegratePipeline {
    pub fn new(device: &wgpu::Device, descriptor: &gpu_dialect::KernelDescriptor) -> Self {
        let label = "pool::integrate";
        let wgsl = gpu_dialect::slang::compile_wgsl(descriptor).expect("compile generated Slang");
        let shader = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some(label),
            source: wgpu::ShaderSource::Wgsl(wgsl.into()),
        });

        let layout_entries = [
            wgpu::BindGroupLayoutEntry {
                binding: 0,
                visibility: wgpu::ShaderStages::COMPUTE,
                ty: wgpu::BindingType::Buffer {
                    ty: wgpu::BufferBindingType::Storage { read_only: true },
                    has_dynamic_offset: false,
                    min_binding_size: None,
                },
                count: None,
            },
            wgpu::BindGroupLayoutEntry {
                binding: 1,
                visibility: wgpu::ShaderStages::COMPUTE,
                ty: wgpu::BindingType::Buffer {
                    ty: wgpu::BufferBindingType::Storage { read_only: true },
                    has_dynamic_offset: false,
                    min_binding_size: None,
                },
                count: None,
            },
            wgpu::BindGroupLayoutEntry {
                binding: 2,
                visibility: wgpu::ShaderStages::COMPUTE,
                ty: wgpu::BindingType::Buffer {
                    ty: wgpu::BufferBindingType::Storage { read_only: false },
                    has_dynamic_offset: false,
                    min_binding_size: None,
                },
                count: None,
            },
        ];
        let bind_group_layout = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            label: Some(label),
            entries: &layout_entries,
        });
        let pipeline_layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: Some(label),
            bind_group_layouts: &[Some(&bind_group_layout)],
            immediate_size: 0,
        });
        let pipeline = device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
            label: Some(label),
            layout: Some(&pipeline_layout),
            module: &shader,
            entry_point: Some(descriptor.entry_point),
            compilation_options: Default::default(),
            cache: None,
        });
        Self {
            _shader: shader,
            bind_group_layout,
            _pipeline_layout: pipeline_layout,
            pipeline,
        }
    }

    pub fn encode(
        &self,
        device: &wgpu::Device,
        encoder: &mut wgpu::CommandEncoder,
        element_count: u32,
        active: &wgpu::Buffer,
        settings: &wgpu::Buffer,
        particles: &wgpu::Buffer,
    ) {
        let label = "pool::integrate";
        let bind_group_entries = [
            wgpu::BindGroupEntry {
                binding: 0,
                resource: active.as_entire_binding(),
            },
            wgpu::BindGroupEntry {
                binding: 1,
                resource: settings.as_entire_binding(),
            },
            wgpu::BindGroupEntry {
                binding: 2,
                resource: particles.as_entire_binding(),
            },
        ];
        let bind_group = device.create_bind_group(&wgpu::BindGroupDescriptor {
            label: Some(label),
            layout: &self.bind_group_layout,
            entries: &bind_group_entries,
        });

        let mut pass = encoder.begin_compute_pass(&wgpu::ComputePassDescriptor {
            label: Some(label),
            timestamp_writes: None,
        });
        pass.set_pipeline(&self.pipeline);
        pass.set_bind_group(0, &bind_group, &[]);
        pass.dispatch_workgroups(element_count.div_ceil(64), 1, 1);
    }
}
